from datetime import datetime, timezone
from typing import List, Optional

from sqlmodel import Field, Relationship, SQLModel


# DATABASE TABLE SCHEMA: Represents exactly how the data looks inside PostgreSQL
class Project(SQLModel, table=True):
    id: Optional[int] = Field(
        default=None, primary_key=True
    )  # The Optional type means that this field can be None, which is the case when we create a new project before it has been saved to the database and assigned an ID.
    name: str = Field(index=True)
    description: Optional[str] = None
    repository_url: Optional[str] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # RELATIONSHIP: Links this project to its tasks in Python memory
    # back_populates means: "If I modify this list, update the 'project' attribute on the Task side too."
    tasks: List["Task"] = Relationship(back_populates="project")


class ProjectCreate(
    SQLModel
):  # This class for validation of inbound data when creating a new project. It doesn't have an ID or timestamps because those are generated by the database.
    name: str
    description: Optional[str] = None
    repository_url: Optional[str] = None


class Task(SQLModel, table=True):
    id: Optional[int] = Field(
        default=None, primary_key=True
    )  # The Optional type means that this field can be None, which is the case when we create a new task before it has been saved to the database and assigned an ID.
    title: str = Field(index=True)
    status: str = Field(default="todo")  # Allowed states : "todo", "progress", "done"
    priority: str = Field(default="medium")  # Allowed states : "low", "medium", "high"
    project_id: int = Field(
        foreign_key="project.id", ondelete="CASCADE"
    )  # This is a foreign key that links this task to a specific project in the database
    # The ondelete="CASCADE" means that if the parent project is deleted, all its associated tasks will also be automatically deleted from the database.

    # RELATIONSHIP: Allows us to easily type `task.project` to get the full parent object
    project: Project = Relationship(back_populates="tasks")


class TaskCreate(
    SQLModel
):  # This class for validation of inbound data when creating a new task. It doesn't have an ID or timestamps because those are generated by the database.
    title: str
    status: Optional[str] = "todo"
    priority: Optional[str] = "medium"
    project_id: int


class DailyLog(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    date: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), index=True
    )

    lines_written: int = Field(default=0)
    hours_spent: float = Field(default=0.0)
    bugs_resolved: int = Field(default=0)
    summary: str = Field(default="")

    # Foreign key to the associated project
    project_id: int = Field(foreign_key="project.id", ondelete="CASCADE")
    # Relationship to the associated project
    project: Project = Relationship()


class DailyLogCreate(SQLModel):
    lines_written: Optional[int] = 0
    hours_spent: Optional[float] = 0.0
    bugs_resolved: Optional[int] = 0
    summary: str
    project_id: int
