"""add update schemas and fix logs user mapping

Revision ID: 3cecb8aa6500
Revises: f5e9f0241d6b
Create Date: 2026-07-06 21:25:54.268393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cecb8aa6500'
down_revision: Union[str, Sequence[str], None] = 'f5e9f0241d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
