"""Add DailyProjectMetric table

Revision ID: c8ff1cccf105
Revises: d6ef64a150a4
Create Date: 2026-07-11 16:01:38.663334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ff1cccf105'
down_revision: Union[str, Sequence[str], None] = 'd6ef64a150a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyprojectmetric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date_recorded', sa.Date(), nullable=False),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailyprojectmetric_date_recorded'), 'dailyprojectmetric', ['date_recorded'], unique=False)
    op.create_index(op.f('ix_dailyprojectmetric_project_id'), 'dailyprojectmetric', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dailyprojectmetric_project_id'), table_name='dailyprojectmetric')
    op.drop_index(op.f('ix_dailyprojectmetric_date_recorded'), table_name='dailyprojectmetric')
    op.drop_table('dailyprojectmetric')
    # ### end Alembic commands ###
