"""Add time tracking to task

Revision ID: d6ef64a150a4
Revises: ec6df006674c
Create Date: 2026-07-11 13:47:51.239834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ef64a150a4'
down_revision: Union[str, Sequence[str], None] = 'ec6df006674c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('session_start_time', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('time_spent', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'time_spent')
    op.drop_column('task', 'session_start_time')
    # ### end Alembic commands ###
