"""add repository aggregation metrics columns

Revision ID: ec6df006674c
Revises: 3cecb8aa6500
Create Date: 2026-07-06 22:11:41.609603

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec6df006674c"
down_revision: Union[str, Sequence[str], None] = "3cecb8aa6500"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Add columns as nullable first so existing rows can handle the addition safely
    op.add_column("project", sa.Column("stars_count", sa.Integer(), nullable=True))
    op.add_column(
        "project", sa.Column("open_issues_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "project",
        sa.Column(
            "last_commit_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )

    # 2. Backfill existing row values to 0 instead of leaving them as NULL
    op.execute("UPDATE project SET stars_count = 0 WHERE stars_count IS NULL")
    op.execute(
        "UPDATE project SET open_issues_count = 0 WHERE open_issues_count IS NULL"
    )

    # 3. Now that no rows are NULL, it is safe to apply the strict NOT NULL constraint!
    op.alter_column("project", "stars_count", nullable=False)
    op.alter_column("project", "open_issues_count", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "last_commit_message")
    op.drop_column("project", "open_issues_count")
    op.drop_column("project", "stars_count")
    # ### end Alembic commands ###
